### PR TITLE
Change dashboard boxes for table.

### LINKED ISSUE #78: Change boxes to table
All the boxes showing skills with level now need to be tables.

### PR DESCRIPTION
**Pull request by lcostantini**
(closes #78)

### CODE REVIEW

**Comment by eloyesp** [comment]
https://rollbar.com/hacker-assessor-st-pr-85/hacker-assessor-st-pr-85/items/1/

There is an error when there is no matching acquirement for a given requirement.

**Comment by lcostantini** [comment]
@eloyesp now is fixed. Thanks!

**Comment by eloyesp** [comment]
Seems fine to me, @mgarciap what do you think?

**Comment by mgarciap** [comment]
@eloyesp is there any colour codes? Red is for what?
Please remove the 'Claim' column / action. This feature will only be available for the evaluatio at this point.

**Comment by eloyesp** [comment]
@mgarciap red shows the big differences (when you need more than 1 level on that skill).

The claim button/action is not part of this issue.

**Pull request merged**
